// 🌟 你的題庫：包含 N5 與 N4(第二課) 單字
export const wordList = [
    // N5 單字 (不分課)
    { word: "食べる", kana: "たべる", zh: "吃", level: "N5" },
    { word: "飲む", kana: "のむ", zh: "喝", level: "N5" },
    { word: "勉強", kana: "べんきょう", zh: "學習、讀書", level: "N5" },
    { word: "猫", kana: "ねこ", zh: "貓咪", level: "N5" },
    { word: "美味しい", kana: "おいしい", zh: "美味的、好吃的", level: "N5" },
    { word: "行く", kana: "いく", zh: "去", level: "N5" },
    { word: "来る", kana: "くる", zh: "來", level: "N5" },
    { word: "見る", kana: "みる", zh: "看", level: "N5" },
    { word: "寝る", kana: "ねる", zh: "睡覺", level: "N5" },
    { word: "起きる", kana: "おきる", zh: "起床", level: "N5" },
    { word: "買う", kana: "かう", zh: "買", level: "N5" },
    { word: "待つ", kana: "まつ", zh: "等待", level: "N5" },
    { word: "読む", kana: "よむ", zh: "閱讀", level: "N5" },
    { word: "書く", kana: "かく", zh: "寫", level: "N5" },
    { word: "聞く", kana: "きく", zh: "聽、問", level: "N5" },
    { word: "新しい", kana: "あたらしい", zh: "新的", level: "N5" },
    { word: "古い", kana: "ふるい", zh: "舊的", level: "N5" },
    { word: "高い", kana: "たかい", zh: "高的、貴的", level: "N5" },
    { word: "安い", kana: "やすい", zh: "便宜的", level: "N5" },
    { word: "大きい", kana: "おおきい", zh: "大的", level: "N5" },
    
    // N4 單字 (指定為 第二課)
    { word: "おかし作り", kana: "おかしづくり", zh: "製作點心", level: "N4", lesson: "2" },
    { word: "すごい", kana: "すごい", zh: "厲害的, 棒的", level: "N4", lesson: "2" },
    { word: "こんな", kana: "こんな", zh: "這樣的", level: "N4", lesson: "2" },
    { word: "やる", kana: "やる", zh: "做, 幹", level: "N4", lesson: "2" },
    { word: "旅館", kana: "りょかん", zh: "(日式)旅館", level: "N4", lesson: "2" },
    { word: "とまる", kana: "とまる", zh: "住宿", level: "N4", lesson: "2" },
    { word: "雪まつり", kana: "ゆきまつり", zh: "雪祭：每年 2 月在北海道札幌市舉行的祭典活動。", level: "N4", lesson: "2" },
    { word: "まつり", kana: "まつり", zh: "節日, 慶典", level: "N4", lesson: "2" },
    { word: "着物", kana: "きもの", zh: "和服", level: "N4", lesson: "2" },
    { word: "どうしたんですか。", kana: "どうしたんですか。", zh: "怎麼了？", level: "N4", lesson: "2" },
    { word: "気分", kana: "きぶん", zh: "心情; 氣氛", level: "N4", lesson: "2" },
    { word: "悪い", kana: "わるい", zh: "壞, 不好", level: "N4", lesson: "2" },
    { word: "ねつ", kana: "ねつ", zh: "發燒, 熱度; 熱情", level: "N4", lesson: "2" },
    { word: "申込書", kana: "もうしこみしょ", zh: "申請書, 申請信", level: "N4", lesson: "2" },
    { word: "事務所", kana: "じむしょ", zh: "辦公室, 事務所", level: "N4", lesson: "2" },
    { word: "説明する", kana: "せつめいする", zh: "解釋, 說明", level: "N4", lesson: "2" },
    { word: "わかる", kana: "わかる", zh: "知道, 明白", level: "N4", lesson: "2" },
    { word: "教える", kana: "おしえる", zh: "教授; 告知", level: "N4", lesson: "2" },
    { word: "あなた", kana: "あなた", zh: "你, 您：稱呼對方時使用的禮貌表達。", level: "N4", lesson: "2" },
    { word: "スピーチ", kana: "スピーチ", zh: "演說, 演講", level: "N4", lesson: "2" },
    { word: "事故", kana: "じこ", zh: "事故", level: "N4", lesson: "2" },
    { word: "不便", kana: "ふべん", zh: "不方便, 不便", level: "N4", lesson: "2" },
    { word: "こわれる", kana: "こわれる", zh: "壞, 破損", level: "N4", lesson: "2" },
    { word: "フランス", kana: "フランス", zh: "法語", level: "N4", lesson: "2" },
    { word: "すし", kana: "すし", zh: "壽司", level: "N4", lesson: "2" },
    { word: "大人", kana: "おとな", zh: "大人, 成人", level: "N4", lesson: "2" },
    { word: "出張", kana: "しゅっちょう", zh: "出差", level: "N4", lesson: "2" },
    { word: "もうすぐ", kana: "もうすぐ", zh: "馬上, 將要, 快要", level: "N4", lesson: "2" },
    { word: "思う", kana: "おもう", zh: "認為, 覺得", level: "N4", lesson: "2" },
    { word: "まちがい", kana: "まちがい", zh: "錯誤, 差錯", level: "N4", lesson: "2" },
    { word: "話", kana: "はなし", zh: "話; 說話", level: "N4", lesson: "2" },
    { word: "本当", kana: "ほんとう", zh: "真的", level: "N4", lesson: "2" },
    { word: "さがす", kana: "さがす", zh: "找", level: "N4", lesson: "2" },
    { word: "電話する", kana: "でんわする", zh: "打電話", level: "N4", lesson: "2" },
    { word: "かける", kana: "かける", zh: "蓋上(醬)", level: "N4", lesson: "2" },
    { word: "よかった", kana: "よかった", zh: "太好了。", level: "N4", lesson: "2" },
    { word: "ソース", kana: "ソース", zh: "醬, 蘸料", level: "N4", lesson: "2" },
    { word: "フルーツ", kana: "フルーツ", zh: "水果", level: "N4", lesson: "2" },
    { word: "かわ", kana: "かわ", zh: "(食物的)皮, 果皮", level: "N4", lesson: "2" },
    { word: "むく", kana: "むく", zh: "削, 剝(皮)", level: "N4", lesson: "2" },
    { word: "シートベルト", kana: "シートベルト", zh: "安全帶", level: "N4", lesson: "2" },
    { word: "運転する", kana: "うんてんする", zh: "駕駛", level: "N4", lesson: "2" },
    { word: "まど", kana: "まど", zh: "窗戶", level: "N4", lesson: "2" },
    { word: "色えんぴつ", kana: "いろえんぴつ", zh: "彩色鉛筆", level: "N4", lesson: "2" },
    { word: "さす", kana: "さす", zh: "撐/打(傘)", level: "N4", lesson: "2" },
    { word: "ハイキング", kana: "ハイキング", zh: "徒步行走, 郊遊", level: "N4", lesson: "2" },
    { word: "さいふ", kana: "さいふ", zh: "錢包", level: "N4", lesson: "2" },
    { word: "さとう", kana: "さとう", zh: "砂糖, 白糖", level: "N4", lesson: "2" },
    { word: "テキスト", kana: "テキスト", zh: "考試, 測驗", level: "N4", lesson: "2" },
    { word: "ありがとうございました。", kana: "ありがとうございました。", zh: "謝謝了。", level: "N4", lesson: "2" },
    { word: "イラスト", kana: "イラスト", zh: "插圖, 解說圖", level: "N4", lesson: "2" },
    { word: "材料", kana: "ざいりょう", zh: "材料", level: "N4", lesson: "2" },
    { word: "もし", kana: "もし", zh: "如果", level: "N4", lesson: "2" },
    { word: "世界", kana: "せかい", zh: "世界", level: "N4", lesson: "2" },
    { word: "困る", kana: "こまる", zh: "困擾, 傷腦筋", level: "N4", lesson: "2" },
    { word: "ホワイトチョコレート", kana: "ホワイトチョコレート", zh: "白巧克力", level: "N4", lesson: "2" },
    { word: "夕飯", kana: "ゆうはん", zh: "晚飯, 晚餐", level: "N4", lesson: "2" },
    { word: "台風", kana: "たいふう", zh: "颱風", level: "N4", lesson: "2" },
    { word: "試合", kana: "しあい", zh: "比賽", level: "N4", lesson: "2" },
    { word: "めんきょ", kana: "めんきょ", zh: "駕照, 駕駛執照", level: "N4", lesson: "2" },
    { word: "どうですか", kana: "どうですか", zh: "如何？", level: "N4", lesson: "2" },
    { word: "近い", kana: "ちかい", zh: "近, 近的", level: "N4", lesson: "2" },
    { word: "工場", kana: "こうじょう", zh: "工廠", level: "N4", lesson: "2" },
    { word: "いつでも", kana: "いつでも", zh: "無論何時", level: "N4", lesson: "2" },
    { word: "むすこ", kana: "むすこ", zh: "兒子", level: "N4", lesson: "2" },
    { word: "見える", kana: "みえる", zh: "映入眼簾, 能看到", level: "N4", lesson: "2" },
    { word: "聞こえる", kana: "きこえる", zh: "聽到, 能聽到", level: "N4", lesson: "2" },
    { word: "赤ちゃん", kana: "あかちゃん", zh: "嬰兒, 寶寶", level: "N4", lesson: "2" },
    { word: "声", kana: "こえ", zh: "聲音", level: "N4", lesson: "2" },
    { word: "ラジオ", kana: "ラジオ", zh: "廣播", level: "N4", lesson: "2" },
    { word: "ほうそう", kana: "ほうそう", zh: "廣播, 播送", level: "N4", lesson: "2" },
    { word: "間に合う", kana: "まにあう", zh: "趕得上, 來得及", level: "N4", lesson: "2" },
    { word: "おくれる", kana: "おくれる", zh: "遲, 遲到", level: "N4", lesson: "2" },
    { word: "たしかめる", kana: "たしかめる", zh: "弄清, 查明, 確認", level: "N4", lesson: "2" },
    { word: "忘れ物", kana: "わすれもの", zh: "遺忘的物品", level: "N4", lesson: "2" },
    { word: "しゅうまつ", kana: "しゅうまつ", zh: "週末", level: "N4", lesson: "2" },
    { word: "やくそく", kana: "やくそく", zh: "約定", level: "N4", lesson: "2" },
    { word: "なぜなら", kana: "なぜなら", zh: "原因是～, 因為～", level: "N4", lesson: "2" },
    { word: "それに", kana: "それに", zh: "並且", level: "N4", lesson: "2" },
    { word: "ところが", kana: "ところが", zh: "然而, 可是, 不過", level: "N4", lesson: "2" },
    { word: "それで", kana: "それで", zh: "於是, 所以", level: "N4", lesson: "2" },
    { word: "フェスティバル", kana: "フェスティバル", zh: "節日, 慶典", level: "N4", lesson: "2" }
];

// 課程資料設定
export const lessonData = {
    "N4": [
        { value: "all", label: "全部 N4 單字" },
        { value: "2", label: "第二課" }
    ]
};

export const modeNames = {
    'zh-to-jp': '🇹🇼 看中文 ➔ 打日文',
    'jp-to-zh': '🇯🇵 看日文 ➔ 打中文',
    'audio': '🎧 聽發音',
    'mixed': '🔀 綜合混合練習'
};
