// 🌟 你的題庫：包含 N5 與 N4(第二課) 單字
export const wordList = [
    // N5 單字 (不分課)
    { word: "食べる", kana: "たべる", zh: "吃", level: "N5" },
    { word: "飲む", kana: "のむ", zh: "喝", level: "N5" },
    { word: "勉強", kana: "べんきょう", zh: "學習、讀書", level: "N5" },
    { word: "猫", kana: "ねこ", zh: "貓咪", level: "N5" },
    { word: "美味しい", kana: "おいしい", zh: "美味的、好吃的", level: "N5" },
    { word: "行く", kana: "いく", zh: "去", level: "N5" },
    { word: "来る", kana: "くる", zh: "來", level: "N5" },
    { word: "見る", kana: "みる", zh: "看", level: "N5" },
    { word: "寝る", kana: "ねる", zh: "睡覺", level: "N5" },
    { word: "起きる", kana: "おきる", zh: "起床", level: "N5" },
    { word: "買う", kana: "かう", zh: "買", level: "N5" },
    { word: "待つ", kana: "まつ", zh: "等待", level: "N5" },
    { word: "読む", kana: "よむ", zh: "閱讀", level: "N5" },
    { word: "書く", kana: "かく", zh: "寫", level: "N5" },
    { word: "聞く", kana: "きく", zh: "聽、問", level: "N5" },
    { word: "新しい", kana: "あたらしい", zh: "新的", level: "N5" },
    { word: "古い", kana: "ふるい", zh: "舊的", level: "N5" },
    { word: "高い", kana: "たかい", zh: "高的、貴的", level: "N5" },
    { word: "安い", kana: "やすい", zh: "便宜的", level: "N5" },
    { word: "大きい", kana: "おおきい", zh: "大的", level: "N5" },

    // N4 單字 (第二課)
    { word: "お菓子作り", kana: "おかしづくり", zh: "製作點心", level: "N4", lesson: "2" },
    { word: "凄い", kana: "すごい", zh: "厲害的, 棒的", level: "N4", lesson: "2" },
    { word: "こんな", kana: "こんな", zh: "這樣的", level: "N4", lesson: "2" },
    { word: "やる", kana: "やる", zh: "做, 幹", level: "N4", lesson: "2" },
    { word: "旅館", kana: "りょかん", zh: "(日式)旅館", level: "N4", lesson: "2" },
    { word: "泊まる", kana: "とまる", zh: "住宿", level: "N4", lesson: "2" },
    { word: "雪まつり", kana: "ゆきまつり", zh: "雪祭：每年 2 月在北海道札幌市舉行的祭典活動。", level: "N4", lesson: "2" },
    { word: "祭り", kana: "まつり", zh: "節日, 慶典", level: "N4", lesson: "2" },
    { word: "着物", kana: "きもの", zh: "和服", level: "N4", lesson: "2" },
    { word: "どうしたんですか。", kana: "どうしたんですか。", zh: "怎麼了？", level: "N4", lesson: "2" },
    { word: "気分", kana: "きぶん", zh: "心情; 氣氛", level: "N4", lesson: "2" },
    { word: "悪い", kana: "わるい", zh: "壞, 不好", level: "N4", lesson: "2" },
    { word: "熱", kana: "ねつ", zh: "發燒, 熱度; 熱情", level: "N4", lesson: "2" },
    { word: "申込書", kana: "もうしこみしょ", zh: "申請書, 申請信", level: "N4", lesson: "2" },
    { word: "事務所", kana: "じむしょ", zh: "辦公室, 事務所", level: "N4", lesson: "2" },
    { word: "説明する", kana: "せつめいする", zh: "解釋, 說明", level: "N4", lesson: "2" },
    { word: "分かる", kana: "わかる", zh: "知道, 明白", level: "N4", lesson: "2" },
    { word: "教える", kana: "おしえる", zh: "教授; 告知", level: "N4", lesson: "2" },
    { word: "あなた", kana: "あなた", zh: "你, 您：稱呼對方時使用的禮貌表達。", level: "N4", lesson: "2" },
    { word: "スピーチ", kana: "スピーチ", zh: "演說, 演講", level: "N4", lesson: "2" },
    { word: "事故", kana: "じこ", zh: "事故", level: "N4", lesson: "2" },
    { word: "不便", kana: "ふべん", zh: "不方便, 不便", level: "N4", lesson: "2" },
    { word: "壊れる", kana: "こわれる", zh: "壞, 破損", level: "N4", lesson: "2" },
    { word: "フランス語", kana: "フランスご", zh: "法語", level: "N4", lesson: "2" },
    { word: "寿司", kana: "すし", zh: "壽司", level: "N4", lesson: "2" },
    { word: "大人", kana: "おとな", zh: "大人, 成人", level: "N4", lesson: "2" },
    { word: "出張", kana: "しゅっちょう", zh: "出差", level: "N4", lesson: "2" },
    { word: "もうすぐ", kana: "もうすぐ", zh: "馬上, 將要, 快要", level: "N4", lesson: "2" },
    { word: "思う", kana: "おもう", zh: "認為, 覺得", level: "N4", lesson: "2" },
    { word: "間違い", kana: "まちがい", zh: "錯誤, 差錯", level: "N4", lesson: "2" },
    { word: "話", kana: "はなし", zh: "話; 說話", level: "N4", lesson: "2" },
    { word: "本当", kana: "ほんとう", zh: "真的", level: "N4", lesson: "2" },
    { word: "探す", kana: "さがす", zh: "找", level: "N4", lesson: "2" },
    { word: "電話する", kana: "でんわする", zh: "打電話", level: "N4", lesson: "2" },
    { word: "かける", kana: "かける", zh: "蓋上(醬)", level: "N4", lesson: "2" },
    { word: "よかった", kana: "よかった", zh: "太好了。", level: "N4", lesson: "2" },
    { word: "ソース", kana: "ソース", zh: "醬, 蘸料", level: "N4", lesson: "2" },
    { word: "フルーツ", kana: "フルーツ", zh: "水果", level: "N4", lesson: "2" },
    { word: "皮", kana: "かわ", zh: "(食物的)皮, 果皮", level: "N4", lesson: "2" },
    { word: "むく", kana: "むく", zh: "削, 剝(皮)", level: "N4", lesson: "2" },
    { word: "シートベルト", kana: "シートベルト", zh: "安全帶", level: "N4", lesson: "2" },
    { word: "運転する", kana: "うんてんする", zh: "駕駛", level: "N4", lesson: "2" },
    { word: "窓", kana: "まど", zh: "窗戶", level: "N4", lesson: "2" },
    { word: "色鉛筆", kana: "いろえんぴつ", zh: "彩色鉛筆", level: "N4", lesson: "2" },
    { word: "差す", kana: "さす", zh: "撐/打(傘)", level: "N4", lesson: "2" },
    { word: "ハイキング", kana: "ハイキング", zh: "徒步行走, 郊遊", level: "N4", lesson: "2" },
    { word: "財布", kana: "さいふ", zh: "錢包", level: "N4", lesson: "2" },
    { word: "砂糖", kana: "さとう", zh: "砂糖, 白糖", level: "N4", lesson: "2" },
    { word: "テキスト", kana: "テキスト", zh: "教材、課本", level: "N4", lesson: "2" },
    { word: "ありがとうございました。", kana: "ありがとうございました。", zh: "謝謝了。", level: "N4", lesson: "2" },
    { word: "イラスト", kana: "イラスト", zh: "插圖, 解說圖", level: "N4", lesson: "2" },
    { word: "材料", kana: "ざいりょう", zh: "材料", level: "N4", lesson: "2" },
    { word: "もし", kana: "もし", zh: "如果", level: "N4", lesson: "2" },
    { word: "世界", kana: "せかい", zh: "世界", level: "N4", lesson: "2" },
    { word: "困る", kana: "こまる", zh: "困擾, 傷腦筋", level: "N4", lesson: "2" },
    { word: "ホワイトチョコレート", kana: "ホワイトチョコレート", zh: "白巧克力", level: "N4", lesson: "2" },
    { word: "夕飯", kana: "ゆうはん", zh: "晚飯, 晚餐", level: "N4", lesson: "2" },
    { word: "台風", kana: "たいふう", zh: "颱風", level: "N4", lesson: "2" },
    { word: "試合", kana: "しあい", zh: "比賽", level: "N4", lesson: "2" },
    { word: "免許", kana: "めんきょ", zh: "駕照, 駕駛執照", level: "N4", lesson: "2" },
    { word: "どうですか", kana: "どうですか", zh: "如何？", level: "N4", lesson: "2" },
    { word: "近い", kana: "ちかい", zh: "近, 近的", level: "N4", lesson: "2" },
    { word: "工場", kana: "こうじょう", zh: "工廠", level: "N4", lesson: "2" },
    { word: "いつでも", kana: "いつでも", zh: "無論何時", level: "N4", lesson: "2" },
    { word: "息子", kana: "むすこ", zh: "兒子", level: "N4", lesson: "2" },
    { word: "見える", kana: "みえる", zh: "映入眼簾, 能看到", level: "N4", lesson: "2" },
    { word: "聞こえる", kana: "きこえる", zh: "聽到, 能聽到", level: "N4", lesson: "2" },
    { word: "赤ちゃん", kana: "あかちゃん", zh: "嬰兒, 寶寶", level: "N4", lesson: "2" },
    { word: "声", kana: "こえ", zh: "聲音", level: "N4", lesson: "2" },
    { word: "ラジオ", kana: "ラジオ", zh: "廣播", level: "N4", lesson: "2" },
    { word: "放送", kana: "ほうそう", zh: "廣播, 播送", level: "N4", lesson: "2" },
    { word: "間に合う", kana: "まにあう", zh: "趕得上, 來得及", level: "N4", lesson: "2" },
    { word: "遅れる", kana: "おくれる", zh: "遲, 遲到", level: "N4", lesson: "2" },
    { word: "確かめる", kana: "たしかめる", zh: "弄清, 查明, 確認", level: "N4", lesson: "2" },
    { word: "忘れ物", kana: "わすれもの", zh: "遺忘的物品", level: "N4", lesson: "2" },
    { word: "週末", kana: "しゅうまつ", zh: "週末", level: "N4", lesson: "2" },
    { word: "約束", kana: "やくそく", zh: "約定", level: "N4", lesson: "2" },
    { word: "なぜなら", kana: "なぜなら", zh: "原因是～, 因為～", level: "N4", lesson: "2" },
    { word: "それに", kana: "それに", zh: "並且", level: "N4", lesson: "2" },
    { word: "ところが", kana: "ところが", zh: "然而, 可是, 不過", level: "N4", lesson: "2" },
    { word: "それで", kana: "それで", zh: "於是, 所以", level: "N4", lesson: "2" },
    { word: "フェスティバル", kana: "フェスティバル", zh: "節日, 慶典", level: "N4", lesson: "2" },

    // N4 單字 (第三課)
    { word: "結婚式", kana: "けっこんしき", zh: "婚禮", level: "N4", lesson: "3" },
    { word: "ご芳名", kana: "ごほうめい", zh: "芳名", level: "N4", lesson: "3" },
    { word: "意味", kana: "いみ", zh: "意思", level: "N4", lesson: "3" },
    { word: "招待する", kana: "しょうたいする", zh: "招待", level: "N4", lesson: "3" },
    { word: "招待状", kana: "しょうたいじょう", zh: "邀請函，邀請信", level: "N4", lesson: "3" },
    { word: "普通", kana: "ふつう", zh: "普通，一般，平常", level: "N4", lesson: "3" },
    { word: "そんなに", kana: "そんなに", zh: "那麼，那麼樣", level: "N4", lesson: "3" },
    { word: "席", kana: "せき", zh: "位子，座位", level: "N4", lesson: "3" },
    { word: "決める", kana: "きめる", zh: "決定", level: "N4", lesson: "3" },
    { word: "礼状", kana: "れいじょう", zh: "感謝信", level: "N4", lesson: "3" },
    { word: "お礼", kana: "おれい", zh: "致謝，謝意；回禮，回敬", level: "N4", lesson: "3" },
    { word: "曇り", kana: "くもり", zh: "陰天", level: "N4", lesson: "3" },
    { word: "晴れる", kana: "はれる", zh: "晴朗", level: "N4", lesson: "3" },
    { word: "三角", kana: "さんかく", zh: "三角形", level: "N4", lesson: "3" },
    { word: "不在", kana: "ふざい", zh: "不在（家）", level: "N4", lesson: "3" },
    { word: "頼む", kana: "たのむ", zh: "拜託，請求，委託", level: "N4", lesson: "3" },
    { word: "誘う", kana: "さそう", zh: "邀請", level: "N4", lesson: "3" },
    { word: "褒める", kana: "ほめる", zh: "表揚，稱讚", level: "N4", lesson: "3" },
    { word: "助ける", kana: "たすける", zh: "幫助，援助，協助，救助", level: "N4", lesson: "3" },
    { word: "連れてくる", kana: "つれてくる", zh: "帶領（人）來", level: "N4", lesson: "3" },
    { word: "紹介する", kana: "しょうかいする", zh: "介紹", level: "N4", lesson: "3" },
    { word: "社長", kana: "しゃちょう", zh: "社長，董事長", level: "N4", lesson: "3" },
    { word: "起こす", kana: "起こす", zh: "叫醒，喚醒", level: "N4", lesson: "3" },
    { word: "風邪", kana: "かぜ", zh: "感冒，傷風", level: "N4", lesson: "3" },
    { word: "風邪をひく", kana: "かぜをひく", zh: "著涼，感冒", level: "N4", lesson: "3" },
    { word: "なかなか", kana: "なかなか", zh: "非常，相當", level: "N4", lesson: "3" },
    { word: "〜キロ", kana: "キロ", zh: "～公里；～公斤", level: "N4", lesson: "3" },
    { word: "これから", kana: "これから", zh: "從現在起，從今往後", level: "N4", lesson: "3" },
    { word: "必ず", kana: "かならず", zh: "必須，一定", level: "N4", lesson: "3" },
    { word: "準備", kana: "じゅんび", zh: "準備", level: "N4", lesson: "3" },
    { word: "留学する", kana: "りゅうがくする", zh: "留學", level: "N4", lesson: "3" },
    { word: "ビザ", kana: "ビザ", zh: "簽證", level: "N4", lesson: "3" },
    { word: "歯医者", kana: "はいしゃ", zh: "牙醫", level: "N4", lesson: "3" },
    { word: "出席する", kana: "しゅっせきする", zh: "出席", level: "N4", lesson: "3" },
    { word: "参加する", kana: "さんかする", zh: "參加", level: "N4", lesson: "3" },
    { word: "お祝い", kana: "おいわい", zh: "慶祝", level: "N4", lesson: "3" },
    { word: "煙草", kana: "たばこ", zh: "菸草，香菸", level: "N4", lesson: "3" },
    { word: "空気", kana: "くうき", zh: "空氣", level: "N4", lesson: "3" },
    { word: "止める", kana: "とめる", zh: "停（車）", level: "N4", lesson: "3" },
    { word: "座る", kana: "すわる", zh: "坐", level: "N4", lesson: "3" },
    { word: "餌", kana: "えさ", zh: "飼料，餌食", level: "N4", lesson: "3" },
    { word: "差し上げる", kana: "さしあげる", zh: "給予（「あげる」的謙讓語）", level: "N4", lesson: "3" },
    { word: "カタログ", kana: "カタログ", zh: "商品目錄", level: "N4", lesson: "3" },
    { word: "エアコン", kana: "エアコン", zh: "空調，冷氣", level: "N4", lesson: "3" },
    { word: "プリント", kana: "プリント", zh: "列印出來的文件，印刷物", level: "N4", lesson: "3" },
    { word: "下がる", kana: "さがる", zh: "下降，降落；降低，衰退", level: "N4", lesson: "3" },
    { word: "意見", kana: "いけん", zh: "意見，建議", level: "N4", lesson: "3" },
    { word: "垃圾箱", kana: "ごみばこ", zh: "垃圾桶", level: "N4", lesson: "3" },
    { word: "少ない", kana: "すくない", zh: "少", level: "N4", lesson: "3" },
    { word: "増やす", kana: "ふやす", zh: "增加，添加", level: "N4", lesson: "3" },
    { word: "考える", kana: "かんがえる", zh: "思考", level: "N4", lesson: "3" },
    { word: "眠い", kana: "ねむい", zh: "睏，困倦，想睡覺", level: "N4", lesson: "3" },
    { word: "前の日", kana: "まえのひ", zh: "前一天", level: "N4", lesson: "3" },
    { word: "相談する", kana: "そうだんする", zh: "諮詢；商量", level: "N4", lesson: "3" },
    { word: "最近", kana: "さいきん", zh: "最近", level: "N4", lesson: "3" },
    { word: "卒業する", kana: "そつぎょうする", zh: "畢業", level: "N4", lesson: "3" },
    { word: "大学院", kana: "だいがくいん", zh: "大學研究所", level: "N4", lesson: "3" },

    // N4 單字 (第四課)
    { word: "クリーニング", kana: "クリーニング", zh: "洗衣店、乾洗", level: "N4", lesson: "4" },
    { word: "人口", kana: "じんこう", zh: "人口", level: "N4", lesson: "4" },
    { word: "花火", kana: "はなび", zh: "煙火", level: "N4", lesson: "4" },
    { word: "勝つ", kana: "かつ", zh: "贏、獲勝", level: "N4", lesson: "4" },
    { word: "約", kana: "やく", zh: "大約、大致", level: "N4", lesson: "4" },
    { word: "ランナー", kana: "ランナー", zh: "跑者、跑步的人", level: "N4", lesson: "4" },
    { word: "応援する", kana: "おうえんする", zh: "加油、聲援", level: "N4", lesson: "4" },
    { word: "申し込み", kana: "もうしこみ", zh: "申請、報名", level: "N4", lesson: "4" },
    { word: "以上", kana: "いじょう", zh: "以上、結束", level: "N4", lesson: "4" },
    { word: "チャリティー", kana: "チャリティー", zh: "慈善、慈善事業", level: "N4", lesson: "4" },
    { word: "植える", kana: "うえる", zh: "種植、栽種", level: "N4", lesson: "4" },
    { word: "社会", kana: "しゃかい", zh: "社會", level: "N4", lesson: "4" },
    { word: "秋", kana: "あき", zh: "秋天", level: "N4", lesson: "4" },
    { word: "集める", kana: "あつめる", zh: "收集、集合", level: "N4", lesson: "4" },
    { word: "周り", kana: "まわり", zh: "周圍、附近", level: "N4", lesson: "4" },
    { word: "亀", kana: "かめ", zh: "烏龜", level: "N4", lesson: "4" },
    { word: "飾る", kana: "かざる", zh: "裝飾", level: "N4", lesson: "4" },
    { word: "アフリカ", kana: "アフリカ", zh: "非洲", level: "N4", lesson: "4" },
    { word: "納豆", kana: "なっとう", zh: "納豆", level: "N4", lesson: "4" },
    { word: "ニューヨーク", kana: "ニューヨーク", zh: "紐約", level: "N4", lesson: "4" },
    { word: "ミュージカル", kana: "ミュージカル", zh: "音樂劇", level: "N4", lesson: "4" },
    { word: "歌舞伎", kana: "かぶき", zh: "歌舞伎", level: "N4", lesson: "4" },
    { word: "自動車", kana: "じどうしゃ", zh: "汽車", level: "N4", lesson: "4" },
    { word: "電話番号", kana: "でんわばんごう", zh: "電話號碼", level: "N4", lesson: "4" },
    { word: "番号", kana: "ばんごう", zh: "號碼", level: "N4", lesson: "4" },
    { word: "さあ", kana: "さあ", zh: "來吧、喂", level: "N4", lesson: "4" },
    { word: "必要", kana: "ひつよう", zh: "必要、必需", level: "N4", lesson: "4" },
    { word: "ボタン", kana: "ボタン", zh: "按鈕、鈕扣", level: "N4", lesson: "4" },
    { word: "押す", kana: "おす", zh: "按、推", level: "N4", lesson: "4" },
    { word: "パスポート", kana: "パスポート", zh: "護照", level: "N4", lesson: "4" },
    { word: "足りる", kana: "たりる", zh: "足夠", level: "N4", lesson: "4" },
    { word: "音", kana: "おと", zh: "聲音、響聲", level: "N4", lesson: "4" },
    { word: "～メートル", kana: "～メートル", zh: "公尺、米", level: "N4", lesson: "4" },
    { word: "橋", kana: "はし", zh: "橋", level: "N4", lesson: "4" },
    { word: "建物", kana: "たてもの", zh: "建築物", level: "N4", lesson: "4" },
    { word: "渡る", kana: "わたる", zh: "過、渡", level: "N4", lesson: "4" },
    { word: "曲がる", kana: "まがる", zh: "轉彎、彎曲", level: "N4", lesson: "4" },
    { word: "モスクワ", kana: "モスクワ", zh: "莫斯科", level: "N4", lesson: "4" },
    { word: "髪", kana: "かみ", zh: "頭髮", level: "N4", lesson: "4" },
    { word: "スカイツリー", kana: "スカイツリー", zh: "晴空塔", level: "N4", lesson: "4" },
    { word: "東京タワー", kana: "とうきょうタワー", zh: "東京鐵塔", level: "N4", lesson: "4" },
    { word: "パレード", kana: "パレード", zh: "遊行", level: "N4", lesson: "4" },
    { word: "昔", kana: "むかし", zh: "以前、從前", level: "N4", lesson: "4" },
    { word: "釣る", kana: "つる", zh: "釣（魚）", level: "N4", lesson: "4" },
    { word: "この間", kana: "このあいだ", zh: "前些天、最近", level: "N4", lesson: "4" },
    { word: "先月", kana: "せんげつ", zh: "上個月", level: "N4", lesson: "4" },
    { word: "速い", kana: "はやい", zh: "快的、迅速的", level: "N4", lesson: "4" },
    { word: "運ぶ", kana: "はこぶ", zh: "搬運、運送", level: "N4", lesson: "4" },
    { word: "タイ", kana: "タイ", zh: "泰國", level: "N4", lesson: "4" },
    { word: "バンコク", kana: "バンコク", zh: "曼谷", level: "N4", lesson: "4" },
    { word: "役に立つ", kana: "やくにたつ", zh: "有用、有幫助", level: "N4", lesson: "4" },
    { word: "今夜", kana: "こんや", zh: "今晚", level: "N4", lesson: "4" },
    { word: "開く", kana: "ひらく", zh: "舉辦（派對）、打開", level: "N4", lesson: "4" },
    { word: "入学式", kana: "にゅうがくしき", zh: "入學典禮", level: "N4", lesson: "4" },
    { word: "毎年", kana: "まいとし", zh: "每年", level: "N4", lesson: "4" },
    { word: "行う", kana: "おこなう", zh: "舉行、進行、實施", level: "N4", lesson: "4" },
    { word: "日本酒", kana: "にほんしゅ", zh: "日本酒", level: "N4", lesson: "4" },
    { word: "米", kana: "こめ", zh: "米", level: "N4", lesson: "4" },
    { word: "建てる", kana: "たてる", zh: "建造、蓋", level: "N4", lesson: "4" },
    { word: "スピーチ大会", kana: "スピーチたいかい", zh: "演講大賽", level: "N4", lesson: "4" },
    { word: "～大会", kana: "～たいかい", zh: "～大賽", level: "N4", lesson: "4" },
    { word: "輸出する", kana: "ゆしゅつする", zh: "出口、輸出", level: "N4", lesson: "4" },
    { word: "心", kana: "こころ", zh: "心、心靈", level: "N4", lesson: "4" },
    { word: "発明する", kana: "はつめいする", zh: "發明", level: "N4", lesson: "4" },
    { word: "ホーム", kana: "ホーム", zh: "月台", level: "N4", lesson: "4" },
    { word: "落ちる", kana: "おちる", zh: "掉落、落下", level: "N4", lesson: "4" },
    { word: "男性", kana: "だんせい", zh: "男性", level: "N4", lesson: "4" },
    { word: "駅員", kana: "えきいん", zh: "站務員", level: "N4", lesson: "4" },
    { word: "屋台", kana: "やたい", zh: "攤位、路邊攤", level: "N4", lesson: "4" },
    { word: "匂い", kana: "におい", zh: "味道、氣味", level: "N4", lesson: "4" },
    { word: "フォー", kana: "フォー", zh: "越南河粉", level: "N4", lesson: "4" },
    { word: "止まる", kana: "とまる", zh: "停止、停住", level: "N4", lesson: "4" },
    { word: "點く", kana: "つく", zh: "（燈）亮、開啟", level: "N4", lesson: "4" },
    { word: "割れる", kana: "われる", zh: "破裂、碎裂", level: "N4", lesson: "4" },
    { word: "カーテン", kana: "カーテン", zh: "窗簾", level: "N4", lesson: "4" },
    { word: "床", kana: "ゆか", zh: "地板", level: "N4", lesson: "4" },
    { word: "ドア", kana: "ドア", zh: "門", level: "N4", lesson: "4" },
    { word: "濡れる", kana: "ぬれる", zh: "濕、淋濕", level: "N4", lesson: "4" },
    { word: "折れる", kana: "おれる", zh: "折斷", level: "N4", lesson: "4" },
    { word: "破れる", kana: "やぶれる", zh: "撕裂、破掉", level: "N4", lesson: "4" },
    { word: "カレーライス", kana: "カレーライス", zh: "咖哩飯", level: "N4", lesson: "4" },
    { word: "味", kana: "あじ", zh: "味道", level: "N4", lesson: "4" },
    { word: "コピー機", kana: "コピーき", zh: "影印機", level: "N4", lesson: "4" },
    { word: "半分", kana: "はんぶん", zh: "一半", level: "N4", lesson: "4" },
    { word: "～点", kana: "～てん", zh: "～分（分數）", level: "N4", lesson: "4" },
    { word: "可愛い", kana: "かわいい", zh: "可愛的", level: "N4", lesson: "4" },
    { word: "頑張る", kana: "がんばる", zh: "努力、加油", level: "N4", lesson: "4" },
    { word: "汚れ", kana: "よごれ", zh: "污垢、髒污", level: "N4", lesson: "4" }
];

// 課程資料設定
export const lessonData = {
    "N4": [
        { value: "all", label: "全部 N4 單字" },
        { value: "2", label: "第二課" },
        { value: "3", label: "第三課" },
        { value: "4", label: "第四課" }
    ]
};

export const modeNames = {
    'zh-to-jp': '🇹🇼 看中文 ➔ 打日文',
    'jp-to-zh': '🇯🇵 看日文 ➔ 打中文',
    'audio': '🎧 聽發音',
    'mixed': '🔀 綜合混合練習',
    'flashcard': '📇 閃卡記憶模式'
};
