// 🌟 你的題庫：包含 N5 與 N4(第二課) 單字
export const wordList = [
    // N5 單字 (不分課)
    { word: "食べる", kana: "たべる", zh: "吃", level: "N5" },
    { word: "飲む", kana: "のむ", zh: "喝", level: "N5" },
    { word: "勉強", kana: "べんきょう", zh: "學習、讀書", level: "N5" },
    { word: "猫", kana: "ねこ", zh: "貓咪", level: "N5" },
    { word: "美味しい", kana: "おいしい", zh: "美味的、好吃的", level: "N5" },
    { word: "行く", kana: "いく", zh: "去", level: "N5" },
    { word: "来る", kana: "くる", zh: "來", level: "N5" },
    { word: "見る", kana: "みる", zh: "看", level: "N5" },
    { word: "寝る", kana: "ねる", zh: "睡覺", level: "N5" },
    { word: "起きる", kana: "おきる", zh: "起床", level: "N5" },
    { word: "買う", kana: "かう", zh: "買", level: "N5" },
    { word: "待つ", kana: "まつ", zh: "等待", level: "N5" },
    { word: "読む", kana: "よむ", zh: "閱讀", level: "N5" },
    { word: "書く", kana: "かく", zh: "寫", level: "N5" },
    { word: "聞く", kana: "きく", zh: "聽、問", level: "N5" },
    { word: "新しい", kana: "あたらしい", zh: "新的", level: "N5" },
    { word: "古い", kana: "ふるい", zh: "舊的", level: "N5" },
    { word: "高い", kana: "たかい", zh: "高的、貴的", level: "N5" },
    { word: "安い", kana: "やすい", zh: "便宜的", level: "N5" },
    { word: "大きい", kana: "おおきい", zh: "大的", level: "N5" },
    
    // N4 單字 (指定為 第二課)
    { word: "おかし作り", kana: "おかしづくり", zh: "製作點心", level: "N4", lesson: "2" },
    { word: "すごい", kana: "すごい", zh: "厲害的, 棒的", level: "N4", lesson: "2" },
    { word: "こんな", kana: "こんな", zh: "這樣的", level: "N4", lesson: "2" },
    { word: "やる", kana: "やる", zh: "做, 幹", level: "N4", lesson: "2" },
    { word: "旅館", kana: "りょかん", zh: "(日式)旅館", level: "N4", lesson: "2" },
    { word: "とまる", kana: "とまる", zh: "住宿", level: "N4", lesson: "2" },
    { word: "雪まつり", kana: "ゆきまつり", zh: "雪祭：每年 2 月在北海道札幌市舉行的祭典活動。", level: "N4", lesson: "2" },
    { word: "まつり", kana: "まつり", zh: "節日, 慶典", level: "N4", lesson: "2" },
    { word: "着物", kana: "きもの", zh: "和服", level: "N4", lesson: "2" },
    { word: "どうしたんですか。", kana: "どうしたんですか。", zh: "怎麼了？", level: "N4", lesson: "2" },
    { word: "気分", kana: "きぶん", zh: "心情; 氣氛", level: "N4", lesson: "2" },
    { word: "悪い", kana: "わるい", zh: "壞, 不好", level: "N4", lesson: "2" },
    { word: "ねつ", kana: "ねつ", zh: "發燒, 熱度; 熱情", level: "N4", lesson: "2" },
    { word: "申込書", kana: "もうしこみしょ", zh: "申請書, 申請信", level: "N4", lesson: "2" },
    { word: "事務所", kana: "じむしょ", zh: "辦公室, 事務所", level: "N4", lesson: "2" },
    { word: "説明する", kana: "せつめいする", zh: "解釋, 說明", level: "N4", lesson: "2" },
    { word: "わかる", kana: "わかる", zh: "知道, 明白", level: "N4", lesson: "2" },
    { word: "教える", kana: "おしえる", zh: "教授; 告知", level: "N4", lesson: "2" },
    { word: "あなた", kana: "あなた", zh: "你, 您：稱呼對方時使用的禮貌表達。", level: "N4", lesson: "2" },
    { word: "スピーチ", kana: "スピーチ", zh: "演說, 演講", level: "N4", lesson: "2" },
    { word: "事故", kana: "じこ", zh: "事故", level: "N4", lesson: "2" },
    { word: "不便", kana: "ふべん", zh: "不方便, 不便", level: "N4", lesson: "2" },
    { word: "こわれる", kana: "こわれる", zh: "壞, 破損", level: "N4", lesson: "2" },
    { word: "フランス", kana: "フランス", zh: "法語", level: "N4", lesson: "2" },
    { word: "すし", kana: "すし", zh: "壽司", level: "N4", lesson: "2" },
    { word: "大人", kana: "おとな", zh: "大人, 成人", level: "N4", lesson: "2" },
    { word: "出張", kana: "しゅっちょう", zh: "出差", level: "N4", lesson: "2" },
    { word: "もうすぐ", kana: "もうすぐ", zh: "馬上, 將要, 快要", level: "N4", lesson: "2" },
    { word: "思う", kana: "おもう", zh: "認為, 覺得", level: "N4", lesson: "2" },
    { word: "まちがい", kana: "まちがい", zh: "錯誤, 差錯", level: "N4", lesson: "2" },
    { word: "話", kana: "はなし", zh: "話; 說話", level: "N4", lesson: "2" },
    { word: "本当", kana: "ほんとう", zh: "真的", level: "N4", lesson: "2" },
    { word: "さがす", kana: "さがす", zh: "找", level: "N4", lesson: "2" },
    { word: "電話する", kana: "でんわする", zh: "打電話", level: "N4", lesson: "2" },
    { word: "かける", kana: "かける", zh: "蓋上(醬)", level: "N4", lesson: "2" },
    { word: "よかった", kana: "よかった", zh: "太好了。", level: "N4", lesson: "2" },
    { word: "ソース", kana: "ソース", zh: "醬, 蘸料", level: "N4", lesson: "2" },
    { word: "フルーツ", kana: "フルーツ", zh: "水果", level: "N4", lesson: "2" },
    { word: "かわ", kana: "かわ", zh: "(食物的)皮, 果皮", level: "N4", lesson: "2" },
    { word: "むく", kana: "むく", zh: "削, 剝(皮)", level: "N4", lesson: "2" },
    { word: "シートベルト", kana: "シートベルト", zh: "安全帶", level: "N4", lesson: "2" },
    { word: "運転する", kana: "うんてんする", zh: "駕駛", level: "N4", lesson: "2" },
    { word: "まど", kana: "まど", zh: "窗戶", level: "N4", lesson: "2" },
    { word: "色えんぴつ", kana: "いろえんぴつ", zh: "彩色鉛筆", level: "N4", lesson: "2" },
    { word: "さす", kana: "さす", zh: "撐/打(傘)", level: "N4", lesson: "2" },
    { word: "ハイキング", kana: "ハイキング", zh: "徒步行走, 郊遊", level: "N4", lesson: "2" },
    { word: "さいふ", kana: "さいふ", zh: "錢包", level: "N4", lesson: "2" },
    { word: "さとう", kana: "さとう", zh: "砂糖, 白糖", level: "N4", lesson: "2" },
    { word: "テキスト", kana: "テキスト", zh: "考試, 測驗", level: "N4", lesson: "2" },
    { word: "ありがとうございました。", kana: "ありがとうございました。", zh: "謝謝了。", level: "N4", lesson: "2" },
    { word: "イラスト", kana: "イラスト", zh: "插圖, 解說圖", level: "N4", lesson: "2" },
    { word: "材料", kana: "ざいりょう", zh: "材料", level: "N4", lesson: "2" },
    { word: "もし", kana: "もし", zh: "如果", level: "N4", lesson: "2" },
    { word: "世界", kana: "せかい", zh: "世界", level: "N4", lesson: "2" },
    { word: "困る", kana: "こまる", zh: "困擾, 傷腦筋", level: "N4", lesson: "2" },
    { word: "ホワイトチョコレート", kana: "ホワイトチョコレート", zh: "白巧克力", level: "N4", lesson: "2" },
    { word: "夕飯", kana: "ゆうはん", zh: "晚飯, 晚餐", level: "N4", lesson: "2" },
    { word: "台風", kana: "たいふう", zh: "颱風", level: "N4", lesson: "2" },
    { word: "試合", kana: "しあい", zh: "比賽", level: "N4", lesson: "2" },
    { word: "めんきょ", kana: "めんきょ", zh: "駕照, 駕駛執照", level: "N4", lesson: "2" },
    { word: "どうですか", kana: "どうですか", zh: "如何？", level: "N4", lesson: "2" },
    { word: "近い", kana: "ちかい", zh: "近, 近的", level: "N4", lesson: "2" },
    { word: "工場", kana: "こうじょう", zh: "工廠", level: "N4", lesson: "2" },
    { word: "いつでも", kana: "いつでも", zh: "無論何時", level: "N4", lesson: "2" },
    { word: "むすこ", kana: "むすこ", zh: "兒子", level: "N4", lesson: "2" },
    { word: "見える", kana: "みえる", zh: "映入眼簾, 能看到", level: "N4", lesson: "2" },
    { word: "聞こえる", kana: "きこえる", zh: "聽到, 能聽到", level: "N4", lesson: "2" },
    { word: "赤ちゃん", kana: "あかちゃん", zh: "嬰兒, 寶寶", level: "N4", lesson: "2" },
    { word: "声", kana: "こえ", zh: "聲音", level: "N4", lesson: "2" },
    { word: "ラジオ", kana: "ラジオ", zh: "廣播", level: "N4", lesson: "2" },
    { word: "ほうそう", kana: "ほうそう", zh: "廣播, 播送", level: "N4", lesson: "2" },
    { word: "間に合う", kana: "まにあう", zh: "趕得上, 來得及", level: "N4", lesson: "2" },
    { word: "おくれる", kana: "おくれる", zh: "遲, 遲到", level: "N4", lesson: "2" },
    { word: "たしかめる", kana: "たしかめる", zh: "弄清, 查明, 確認", level: "N4", lesson: "2" },
    { word: "忘れ物", kana: "わすれもの", zh: "遺忘的物品", level: "N4", lesson: "2" },
    { word: "しゅうまつ", kana: "しゅうまつ", zh: "週末", level: "N4", lesson: "2" },
    { word: "やくそく", kana: "やくそく", zh: "約定", level: "N4", lesson: "2" },
    { word: "なぜなら", kana: "なぜなら", zh: "原因是～, 因為～", level: "N4", lesson: "2" },
    { word: "それに", kana: "それに", zh: "並且", level: "N4", lesson: "2" },
    { word: "ところが", kana: "ところが", zh: "然而, 可是, 不過", level: "N4", lesson: "2" },
    { word: "それで", kana: "それで", zh: "於是, 所以", level: "N4", lesson: "2" },
    { word: "フェスティバル", kana: "フェスティバル", zh: "節日, 慶典", level: "N4", lesson: "2" },
    
    // N4 單字 (第三課)
    { word: "けっこんしき", kana: "けっこんしき", zh: "婚禮", level: "N4", lesson: "3" },
    { word: "ごほうめい", kana: "ごほうめい", zh: "芳名", level: "N4", lesson: "3" },
    { word: "意味", kana: "いみ", zh: "意思", level: "N4", lesson: "3" },
    { word: "しょうたいする", kana: "しょうたいする", zh: "招待", level: "N4", lesson: "3" },
    { word: "しょうたいじょう", kana: "しょうたいじょう", zh: "邀請函，邀請信", level: "N4", lesson: "3" },
    { word: "ふつう", kana: "ふつう", zh: "普通，一般，平常", level: "N4", lesson: "3" },
    { word: "そんなに", kana: "そんなに", zh: "那麼，那麼樣", level: "N4", lesson: "3" },
    { word: "席", kana: "せき", zh: "位子，座位", level: "N4", lesson: "3" },
    { word: "決める", kana: "きめる", zh: "決定", level: "N4", lesson: "3" },
    { word: "礼状", kana: "れいじょう", zh: "感謝信", level: "N4", lesson: "3" },
    { word: "お礼", kana: "おれい", zh: "致謝，謝意；回禮，回敬", level: "N4", lesson: "3" },
    { word: "くもり", kana: "くもり", zh: "陰天", level: "N4", lesson: "3" },
    { word: "はれる", kana: "はれる", zh: "晴朗", level: "N4", lesson: "3" },
    { word: "さんかく(△)", kana: "さんかく", zh: "三角形", level: "N4", lesson: "3" },
    { word: "不在", kana: "ふざい", zh: "不在（家）", level: "N4", lesson: "3" },
    { word: "頼む", kana: "たのむ", zh: "拜託，請求，委託", level: "N4", lesson: "3" },
    { word: "さそう", kana: "さそう", zh: "邀請", level: "N4", lesson: "3" },
    { word: "ほめる", kana: "ほめる", zh: "表揚，稱讚", level: "N4", lesson: "3" },
    { word: "助ける", kana: "たすける", zh: "幫助，援助，協助，救助", level: "N4", lesson: "3" },
    { word: "連れてくる", kana: "つれてくる", zh: "帶領（人）來", level: "N4", lesson: "3" },
    { word: "しょうかいする", kana: "しょうかいする", zh: "介紹", level: "N4", lesson: "3" },
    { word: "社長", kana: "しゃちょう", zh: "社長，董事長", level: "N4", lesson: "3" },
    { word: "起こす", kana: "おこす", zh: "叫醒，喚醒", level: "N4", lesson: "3" },
    { word: "かぜ", kana: "かぜ", zh: "感冒，傷風", level: "N4", lesson: "3" },
    { word: "かぜをひく", kana: "かぜをひく", zh: "著涼，感冒", level: "N4", lesson: "3" },
    { word: "なかなか", kana: "なかなか", zh: "非常，相當", level: "N4", lesson: "3" },
    { word: "〜キロ", kana: "キロ", zh: "～公里；～公斤", level: "N4", lesson: "3" },
    { word: "これから", kana: "これから", zh: "從現在起，從今往後", level: "N4", lesson: "3" },
    { word: "かならず", kana: "かならず", zh: "必須，一定", level: "N4", lesson: "3" },
    { word: "じゅんび", kana: "じゅんび", zh: "準備", level: "N4", lesson: "3" },
    { word: "留学する", kana: "りゅうがくする", zh: "留學", level: "N4", lesson: "3" },
    { word: "ビザ", kana: "ビザ", zh: "簽證", level: "N4", lesson: "3" },
    { word: "歯医者", kana: "はいしゃ", zh: "牙醫", level: "N4", lesson: "3" },
    { word: "出席する", kana: "しゅっせきする", zh: "出席", level: "N4", lesson: "3" },
    { word: "参加する", kana: "さんかする", zh: "參加", level: "N4", lesson: "3" },
    { word: "おいわい", kana: "おいわい", zh: "慶祝", level: "N4", lesson: "3" },
    { word: "たばこ", kana: "たばこ", zh: "菸草，香菸", level: "N4", lesson: "3" },
    { word: "空気", kana: "くうき", zh: "空氣", level: "N4", lesson: "3" },
    { word: "止める", kana: "とめる", zh: "停（車）", level: "N4", lesson: "3" },
    { word: "座る", kana: "すわる", zh: "坐", level: "N4", lesson: "3" },
    { word: "えさ", kana: "えさ", zh: "飼料，餌食", level: "N4", lesson: "3" },
    { word: "さしあげる", kana: "さしあげる", zh: "給予（「あげる」的謙讓語）", level: "N4", lesson: "3" },
    { word: "カタログ", kana: "カタログ", zh: "商品目錄", level: "N4", lesson: "3" },
    { word: "エアコン", kana: "エアコン", zh: "空調，冷氣", level: "N4", lesson: "3" },
    { word: "プリント", kana: "プリント", zh: "列印出來的文件，印刷物", level: "N4", lesson: "3" },
    { word: "下がる", kana: "さがる", zh: "下降，降落；降低，衰退", level: "N4", lesson: "3" },
    { word: "意見", kana: "いけん", zh: "意見，建議", level: "N4", lesson: "3" },
    { word: "ごみばこ", kana: "ごみばこ", zh: "垃圾桶", level: "N4", lesson: "3" },
    { word: "少ない", kana: "すくない", zh: "少", level: "N4", lesson: "3" },
    { word: "ふやす", kana: "ふやす", zh: "增加，添加", level: "N4", lesson: "3" },
    { word: "考える", kana: "かんがえる", zh: "思考", level: "N4", lesson: "3" },
    { word: "ねむい", kana: "ねむい", zh: "睏，困倦，想睡覺", level: "N4", lesson: "3" },
    { word: "前の日", kana: "まえのひ", zh: "前一天", level: "N4", lesson: "3" },
    { word: "そうだんする", kana: "そうだんする", zh: "諮詢；商量", level: "N4", lesson: "3" },
    { word: "最近", kana: "さいきん", zh: "最近", level: "N4", lesson: "3" },
    { word: "卒業する", kana: "そつぎょうする", zh: "畢業", level: "N4", lesson: "3" },
    { word: "大学院", kana: "だいがくいん", zh: "大學研究所", level: "N4", lesson: "3" }
];

// 課程資料設定
export const lessonData = {
    "N4": [
        { value: "all", label: "全部 N4 單字" },
        { value: "2", label: "第二課" },
        { value: "3", label: "第三課" }
    ]
};

export const modeNames = {
    'zh-to-jp': '🇹🇼 看中文 ➔ 打日文',
    'jp-to-zh': '🇯🇵 看日文 ➔ 打中文',
    'audio': '🎧 聽發音',
    'mixed': '🔀 綜合混合練習',
    'flashcard': '📇 閃卡記憶模式'
};
